title: Minimal theme
logo: /assets/img/logo.png
description: 
<p align="center">
<a href="www.linkedin.com/in/kifah-muqalled-92270463">LinkedIn</a>
<br>   
  I'm working on Machine learning problems.
<br>
</p>
theme: jekyll-theme-minimal
